site_name: benchcab

# Needed to generate the canonical_url for each pages that are 
# then used to create the sitemap for search engine indexing
site_url: https://cable-lsm.github.io/benchcab/
# Git repository
repo_url: https://github.com/CABLE-LSM/benchcab
repo_name: benchcab
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

theme:
  name: material
  palette:
    - scheme: light
      primary: red
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  version:
    provider: mike
    
plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
# Navigation
nav:
  - About: index.md
  - User Guide:
    - user_guide/index.md
    - user_guide/config_options.md
      